FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y \
      git \
      curl \
      jq \
      iptables \
      dnsutils \
      sudo \
      ca-certificates \
      unzip \
      netcat-traditional && \
    rm -rf /var/lib/apt/lists/*
